#!/bin/sh -e

if snapctl services "${SNAP_NAME}" | grep -q inactive; then
  >&1 echo "Enabling services."
  logger -t ${SNAP_NAME} "Enabling services."

  snapctl start --enable "${SNAP_NAME}" 2>&1 || true

  exit 0
fi

>&1 echo "Starting services."
logger -t ${SNAP_NAME} "Starting services."
# Service was already enabled, just restart it to make sure the new
# config values are picked up
snapctl restart "${SNAP_NAME}" 2>&1 || true
