name: ros2-exporter-agent
base: core22
version: git
summary: ROS 2 data exporter
description: |
  The ROS 2 data exporter records ROS 2 data as rosbags
  and exports them to an S3 server for later use.

  The daemon daily-rotation will move the bags to
  a new timestamped directory at midnight.
  Make sure to have properly configured the time on the machine.

  Optional parameters:

   # topic recorded (default to all)
   topic-regex
   topic-exclude

   # bag parameters
   max-bag-duration # 5 mins
   max-bag-size # 250 MB

grade: devel
confinement: strict

plugs:
  configuration-read:
    interface: content
    target: $SNAP_COMMON/configuration

apps:
  daily-rotation:
    command: usr/bin/daily-rotation.sh
    daemon: simple
    install-mode: disable
    timer: "00:00" # every day at midnight
  recorder:
    command: usr/bin/record.sh
    daemon: simple
    install-mode: disable
    extensions: [ros2-humble]
    plugs: [network, network-bind]
  synchronization:
    command: usr/bin/sync.sh
    daemon: simple
    install-mode: disable
    timer: "00:00-24:00/288" # every 5 minutes
    plugs: [network, network-bind]

parts:
  ros2bag:
    plugin: colcon
    source: src/ros2bag_support
  exporter-agent:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
      'start-services': usr/bin/
      'stop-services': usr/bin/
      'check-bucket': usr/bin/
    stage-snaps:
      - yq
      - rclone
