name: ros2-exporter-agent
base: core22
version: git
summary: ROS 2 data exporter
description: |
  The ROS 2 data exporter is recording ROS 2 data
  and exporting them on a server for later consultation

  Add you private ssh-key and config file for the storage server in:

   /root/snap/ros2-exporter-agent/common/.ssh/

  The `config` file should look like:

  ```
  Host storage-server
      User <server_user>
      HostName <server_hostname>
      IdentityFile /root/snap/ros2-exporter-agent/common/.ssh/<my_private_key>
      UserKnownHostsFile /root/snap/ros2-exporter-agent/common/.ssh/known_hosts
  ```

  The daemon daily-rotation will move the bags to a new timestamped directory at midnight.
  Make sure to have properly configured the time on the machine.

  Optional parameters:

   # server parameter
   storage-path (default to ~/$HOSTNAME)

   # topic recorded (default to all)
   topic-regex
   topic-exclude

   # bag parameters
   max-bag-duration # 5 mins
   max-bag-size # 250 MB

grade: devel
confinement: strict

plugs:
  rob-cos-common-read:
    interface: content
    target: $SNAP_COMMON/rob-cos-shared-data
  configuration-read:
    interface: content
    target: $SNAP_COMMON/configuration

apps:
  read-configuration:
    command: usr/bin/read-configuration.sh
    daemon: oneshot
    install-mode: disable
    before: [recorder]
  recorder:
    command: usr/bin/record.sh
    daemon: simple
    install-mode: disable
    extensions: [ros2-humble]
    plugs: [network, network-bind]
  synchronization:
    command: usr/bin/sync.sh
    daemon: simple
    install-mode: disable
    timer: "00:00-24:00/720" # every 2 minutes
    plugs: [network, network-bind, rob-cos-common-read]
  daily-rotation:
    command: usr/bin/daily-rotation.sh
    daemon: simple
    install-mode: disable
    timer: "00:00" # every day at midnight
  auto-clean:
    command: usr/bin/auto-clean.sh
    daemon: simple
    install-mode: disable
    timer: "00:00-24:00/288" # every 5 minutes

parts:
  ros2bag:
    plugin: colcon
    source: src/ros2bag_support
