name: ros2-exporter-agent
base: core24
version: git
summary: ROS 2 data exporter
description: |
  The ROS 2 data exporter records ROS 2 data
  and exports them to an S3 bucket for later consultation.

  The daemon daily-rotation will move the bags to a new timestamped directory at midnight.
  Make sure to have properly configured the time on the machine.

  Configuration files can be found in $SNAP_COMMON/.config/

grade: devel
confinement: strict

plugs:
  rosbag2-recorder-parameters:
    interface: confdb
    account: canonical-robotics
    view: cos-rosbag2-recorder/parameters
    role: custodian
  rclone-parameters:
    interface: confdb
    account: canonical-robotics
    view: cos-rclone/parameters
    role: custodian

apps:
  auto-clean:
    command: usr/bin/auto-clean
    daemon: simple
    install-mode: disable
    timer: "00:00-24:00/288" # every 5 minutes
  daily-rotation:
    command: usr/bin/daily-rotation
    daemon: simple
    install-mode: disable
    timer: "00:00" # every day at midnight
  recorder:
    command: usr/bin/record
    daemon: simple
    install-mode: disable
    extensions: [ros2-jazzy]
    plugs: [network, network-bind]
  synchronization:
    command: usr/bin/sync
    daemon: simple
    install-mode: disable
    timer: "00:00-24:00/720" # every 2 minutes
    plugs: [network, network-bind]

parts:
  ros2bag:
    plugin: colcon
    source: src/rosbag2_recorder_support
  rclone:
    plugin: nil
    stage-snaps: [rclone]
    stage-packages: [fd-find]
  local-files:
    plugin: dump
    source: snap/local/scripts
    organize:
      '*': usr/bin/
