#!/bin/sh -e

# now we can start the service
if snapctl services ${SNAP_NAME}.recorder | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.recorder 2>&1 || true
fi

if snapctl services ${SNAP_NAME}.synchronization | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.synchronization 2>&1 || true
fi

if snapctl services ${SNAP_NAME}.daily-rotation | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.daily-rotation 2>&1 || true
fi

if snapctl services ${SNAP_NAME}.auto-clean | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.auto-clean 2>&1 || true
fi
