#!/bin/sh -e

STORAGE_SERVER="$(snapctl get storage-server)"
STORAGE_USER="$(snapctl get storage-user)"

# now we can start the service
if [ -n "${STORAGE_SERVER}" ] && [ -n "${STORAGE_USER}" ]; then
    if snapctl services ${SNAP_NAME}.synchronization | grep -q inactive; then
        snapctl start --enable ${SNAP_NAME}.${SNAP_NAME} 2>&1 || true
    fi
fi
