#!/bin/sh -eu

RCLONE_CONFIGURATION_FILE_PATH="${SNAP_COMMON}/configuration/ros2-exporter-agent/rclone.conf"
ROSBAG2_CONFIGURATION_FILE_PATH="${SNAP_COMMON}/configuration/ros2-exporter-agent/rosbag2-recorder.yaml"

if [ ! -f "${RCLONE_CONFIGURATION_FILE_PATH}" ]; then
    echo "Rclone configuration file '${RCLONE_CONFIGURATION_FILE_PATH}' does not exist."
    exit 1
fi

if [ ! -f "${ROSBAG2_CONFIGURATION_FILE_PATH}" ]; then
    echo "Rosbag2-recorder configuration file '${ROSBAG2_CONFIGURATION_FILE_PATH}' does not exist."
    exit 1
fi

snapctl start --enable "${SNAP_NAME}.read-configuration" 2>&1

"${SNAP}/usr/bin/try-enable-recording.sh"

snapctl restart "${SNAP_NAME}" 2>&1 || true
