#!/usr/bin/env python3

import configparser
import io
import os
import subprocess
import sys

config_file = os.path.join(
    os.environ["SNAP_COMMON"], ".config", "rclone", "rclone.conf"
)

if not os.path.exists(config_file):
    print(f"Config file {config_file} not found")
    sys.exit(1)

# Load INI file
config = configparser.ConfigParser()
with open(config_file) as f:
    config.read_file(f)

# Convert INI file body to string
buf = io.StringIO()
config.write(buf)
ini_str = buf.getvalue()

if ini_str:
    cmd = ["snapctl", "set", "--view", ":rclone-parameters", f"file={ini_str}"]
    subprocess.run(cmd)
