#!/usr/bin/env python3

import os
import subprocess
import sys
import yaml

config_file = os.path.join(
    os.environ["SNAP_COMMON"], ".config", "rosbag2_recorder", "rosbag2_recorder.yaml"
)

if not os.path.exists(config_file):
    print(f"Config file {config_file} not found")
    sys.exit(1)

with open(config_file) as f:
    data = yaml.safe_load(f)

if data:
    cmd = ["snapctl", "set", "--view", ":rosbag2-recorder-parameters", f"file={data}"]
    subprocess.run(cmd)
