#!/bin/bash -eu

RCLONE_CONFIGURATION="$(snapctl get --view :confdb-configuration rclone || true)"
ROSBAG2_RECORDER_CONFIGURATION="$(snapctl get --view :confdb-configuration rosbag2-recorder || true)"


if [[ -n "${RCLONE_CONFIGURATION}" ]]; then
  . "${SNAP}/usr/bin/write-tmp-file.sh" "${RCLONE_CONFIGURATION}" RCLONE_CONFIG_FILE

  if ! rclone listremotes --config "${RCLONE_CONFIG_FILE}"; then
    >&2 echo "Invalid rclone configuration provided in confdb view :confdb-configuration, key rclone."
    logger -t "${SNAP_NAME}" "Invalid rclone configuration provided in confdb view :confdb-configuration, key rclone."
    exit 1
  fi
fi

if [[ -n "${ROSBAG2_RECORDER_CONFIGURATION}" ]]; then
  if ! yq >/dev/null <<<"${ROSBAG2_RECORDER_CONFIGURATION}"; then
    >&2 echo "Invalid YAML provided in rosbag2-recorder."
    logger -t "${SNAP_NAME}" "Invalid YAML provided in rosbag2-recorder."
    exit 1
  fi
fi

"${SNAP}/usr/bin/try-enable-recording.sh"

snapctl restart "${SNAP_NAME}" 2>&1 || true
