#!/usr/bin/env python3

import json
import subprocess
import os
import sys

# Get view
result = subprocess.run(
    ["snapctl", "get", "--view", ":rclone-parameters", "-d"],
    capture_output=True,
    text=True,
)

if result.returncode != 0:
    print(f"No confdb data found: {result.stderr}")
    sys.exit(1)

# Load view output as JSON
view_data = json.loads(result.stdout)

ini_content = view_data.get("file", "\"\"")

config_file = os.path.join(
    os.environ["SNAP_COMMON"], ".config", "rclone", "rclone.conf"
)

os.makedirs(os.path.dirname(config_file), exist_ok=True)
with open(config_file, "w") as f:
    f.write(ini_content)
